# Generated by Django 4.2.4 on 2023-12-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('idInscrito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.DateField()),
                ('fechaInscripcion', models.DateField()),
                ('institucion', models.DateField()),
                ('horaInscripcion', models.DateField()),
                ('estado', models.DateField()),
                ('observacion', models.DateField()),
            ],
        ),
    ]
