# Generated by Django 4.2.4 on 2023-12-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barria_mobile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='estado',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='horaInscripcion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='institucion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='observacion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
