# Generated by Django 4.2.4 on 2023-12-23 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barria_mobile_app', '0002_alter_inscrito_estado_alter_inscrito_horainscripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscrito',
            old_name='idInscrito',
            new_name='id',
        ),
    ]
